-- MySQL Script generated by MySQL Workbench
-- 2020. ápr. 30., csütörtök, 15:49:40 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`memoria_jatek_kep_1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`memoria_jatek_kep_1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`memoria_jatek_kep_1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kep` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `kepek_UNIQUE` (`kep` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`memoria-jatek-felhasznalo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`memoria-jatek-felhasznalo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`memoria-jatek-felhasznalo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nev` VARCHAR(45) NOT NULL,
  `nehezseg` INT NOT NULL,
  `kezdo_datum` DATETIME NOT NULL,
  `befejezo_datum` DATETIME NOT NULL,
  `pont` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nev_UNIQUE` (`nev` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`memoria_jatek_kep_2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`memoria_jatek_kep_2` ;

CREATE TABLE IF NOT EXISTS `mydb`.`memoria_jatek_kep_2` (
  `id` INT NOT NULL,
  `memoria_jatek_kep_1_id` VARCHAR(45) NULL,
  `kep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_memorp_2_1ia_jatek_ke_idx` (`memoria_jatek_kep_1_id` ASC) VISIBLE,
  UNIQUE INDEX `kep_UNIQUE` (`kep` ASC) VISIBLE,
  CONSTRAINT `fk_memorp_2_1ia_jatek_ke`
    FOREIGN KEY (`memoria_jatek_kep_1_id`)
    REFERENCES `mydb`.`memoria_jatek_kep_1` (`kep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
